In [19]:
import pandas as pd

import langid
# langid.classify("Bonjour le monde")  # ('fr', -54.41)
def langid_classify(t):
    return langid.classify(t)[0]

In [60]:
cols = ["timestamp", "text", "permission_processing", "permission_sharing"]
short_nl = pd.read_csv("./responses_short_NL_20260821.csv")
short_nl.columns = cols
short_en = pd.read_csv("./responses_short_EN_20260821.csv")
short_en.columns = cols

short_column_ids = [0, 1, -2, -1]

nl = pd.read_csv("./responses_NL_20260821.csv")
nl = nl.iloc[:, short_column_ids]
nl.columns = cols
en = pd.read_csv("./responses_EN_20260821.csv")
en = en.iloc[:, short_column_ids]
en.columns = cols


combined = pd.concat([short_nl, nl, short_en, en], ignore_index=True)
# combined.timestamp = pd.to_datetime(combined.timestamp, format="%d/%m/%Y %H:%M:%S")
langs = combined.text.apply(langid_classify)
combined["language_code"] = langs
combined = combined.drop_duplicates("text")

In [61]:
combined.to_csv("conversation_starters_20260821.csv")

In [34]:
langs = short_nl.text.apply(langid_classify)
short_nl["language_code"] = langs

langs = short_en.text.apply(langid_classify)
short_en["language_code"] = langs

short = pd.concat([short_nl, short_en])
short.timestamp = pd.to_datetime(short.timestamp, format="%d/%m/%Y %H:%M:%S")
short

,timestamp,text,permission_processing,permission_sharing,language_code
0,2026-07-10 10:36:26,"Moet een designer ""democratisch"" zijn ? Want, ...",Ja,Ja,nl
1,2026-07-30 09:29:35,De laatste keer dat ik geweend heb was,Ja,Ja,nl
2,2026-07-30 23:26:37,"Gaat democratie, de processen en machtsverhoud...",Ja,Ja,nl
3,2026-07-31 09:40:46,Democratie werkt enkel als...,Ja,Ja,nl
4,2026-07-31 09:51:18,Hoe kunnen we vermijden dat er anti-democratis...,Ja,Ja,nl
5,2026-07-31 09:53:09,Zal de liberale democratie de 21ste eeuw overl...,Ja,Ja,nl
6,2026-07-31 10:02:07,"Als jij premier bent, wat is je eerste voorstel?",Ja,Ja,nl
7,2026-07-31 10:11:22,Als het water in onze stad een stem zou hebben...,Ja,Ja,nl
8,2026-07-31 10:11:55,Als de bomen de macht hadden - welke keuzes zo...,Ja,Ja,nl
9,2026-07-31 10:13:17,Als 30% van de bevolking (zij die onze stad be...,Ja,Ja,nl
10,2026-07-31 10:15:02,Hoe zou het zijn mocht bij elke stemming er oo...,Ja,Ja,nl
11,2026-07-31 10:16:18,Wat moeten we het meest subsidiëren in oorlogs...,Ja,Ja,nl
12,2026-07-31 10:16:43,Ik ben vandaag het meest dankbaar voor....,Ja,Ja,nl
13,2026-07-31 10:17:02,Ik ben vandaag het meest ongerust over ....,Ja,Ja,nl
14,2026-07-31 10:17:33,Ik moest recent nog glimlachen bij ...,Ja,Ja,nl
15,2026-08-01 10:35:38,Gezien de voortdurende veranderingen in de sam...,Ja,Ja,nl
16,2026-08-04 22:16:40,Wat zou er in jouw leven veranderen als er plo...,Ja,Ja,nl
17,2026-08-04 22:21:06,Democratie zorgt ervoor dat beslissingen veel ...,Ja,Ja,nl
18,2026-08-05 12:09:37,Compared to the expensive foreign Design-brand...,Ja,Ja,en
19,2026-08-05 12:14:50,Will design adapt to smaller living spaces and...,Ja,Ja,en
20,2026-08-07 16:31:34,Er wordt me steeds verteld dat we in een democ...,Ja,Ja,nl
21,2026-08-07 16:33:12,Door een stem uit te brengen heb je zogezegd i...,Ja,Ja,nl
22,2026-08-07 20:30:45,"Ik heb nog nooit meegedaan aan een betoging, w...",Ja,Ja,nl
23,2026-08-11 17:38:46,Zijn mensen die in een democratie leven gelukk...,Ja,Ja,nl
24,2026-08-13 10:07:48,Hoe ambitieuze ideeën/ambities intact houden i...,Ja,Ja,nl
25,2026-08-13 10:39:03,Hoe vermijden dat 'democratie' afglijdt naar e...,Ja,Ja,nl
26,2026-08-14 11:04:22,Which political system is still a real democracy?,Ja,Ja,en
27,2026-08-19 12:34:18,Waar staat de schoonste boom van Gent? Beschri...,Ja,Ja,nl
28,2026-08-19 12:34:51,Welke burgerlijke wet is de belangrijkste voor...,Ja,Ja,nl
29,2026-08-19 12:35:27,Wie is meer waard voor de samenleving: een hon...,Ja,Ja,nl
30,2026-08-19 12:39:10,Gent is een natuurgebied – mensen leven er met...,Ja,Ja,nl
31,2026-08-19 12:42:51,"Gent is een natuurgebied - mensen merels, bome...",Ja,Ja,nl
0,2026-07-10 10:37:55,Does a designer have to be ‘democratic’? Becau...,Yes,Yes,en
1,2026-07-15 10:34:11,How could a fox vote?,Yes,Yes,en
2,2026-08-10 15:26:51,How can people be more involved in their democ...,Yes,Yes,en
3,2026-08-10 15:27:09,What are the limits of protest?,Yes,Yes,en
4,2026-08-10 15:27:53,But what about those under 18? Shouldn't they ...,Yes,Yes,en
5,2026-08-11 12:44:51,"How can we build a decarbonized, just, feminis...",Yes,Yes,en
6,2026-08-14 08:32:47,"Sometimes, democracy has to be avoided at all ...",Yes,Yes,en
7,2026-08-17 11:31:09,The future of Belgium's democracy is a perment...,Yes,Yes,en
8,2026-08-21 11:46:19,Most people confuse socialism and communism,Yes,Yes,en
9,2026-08-21 11:47:52,The King of Cambodia is the only reigning mona...,Yes,Yes,en

In [7]:
short_en

,Timestamp,"Please share a conversation starter: a short question, unfinished sentence, or evocative thought that invites others to respond.",I consent to my conversation starter (and its translations) being processed by local algorithmic systems.,I consent to my conversation starter (and its translations) being shown as part of the Public Matter(s) exhibition.
0,10/07/2026 10:37:55,Does a designer have to be ‘democratic’? Becau...,Yes,Yes
1,15/07/2026 10:34:11,How could a fox vote?,Yes,Yes
2,10/08/2026 15:26:51,How can people be more involved in their democ...,Yes,Yes
3,10/08/2026 15:27:09,What are the limits of protest?,Yes,Yes
4,10/08/2026 15:27:53,But what about those under 18? Shouldn't they ...,Yes,Yes
5,11/08/2026 12:44:51,"How can we build a decarbonized, just, feminis...",Yes,Yes
6,14/08/2026 08:32:47,"Sometimes, democracy has to be avoided at all ...",Yes,Yes
7,17/08/2026 11:31:09,The future of Belgium's democracy is a perment...,Yes,Yes
8,21/08/2026 11:46:19,Most people confuse socialism and communism,Yes,Yes
9,21/08/2026 11:47:52,The King of Cambodia is the only reigning mona...,Yes,Yes